server:
  port: 8090
spring:
  application:
    name: cloud-movie-localhost
  datasource:
    initialize: true
    platform: h2
    url: jdbc:h2:mem:moviedb;
    username: sa
    password: null
  h2:
    console:
      enabled: true
  session:
    store-type: none

name: green
